<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dbw_mkz" >

  <link name="base_footprint">
  </link>

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 ${centre_grav_z}" rpy="0 0 0"/>
      <mass value="${chassis_weight}"/>
        <inertia
        ixx="${(chassis_weight/12)*((car_width**2)+(car_height**2))}" ixy="0.0" ixz="0.0"
        iyy="${(chassis_weight/12)*((car_width**2)+(car_length**2))}" iyz="0.0"
        izz="${(chassis_weight/12)*((car_height**2)+(car_length**2))}"/>
    </inertial>
    <visual name="chassis">
      <origin xyz="${1.361 - base_link_x} 0 -0.33647" rpy="0 0 ${pi/2}"/>
      <geometry>
        <mesh filename="package://car_meshes/meshes/mondeo_blue.dae" scale="1 1 1"/>
      </geometry>
      <material name="black.001"/>
    </visual>
    <collision name="chassis_collision">
      <origin xyz="${1.4621 - base_link_x} -0.03046 0.350609" rpy="${pi/2} 0 -${pi}"/>
      <geometry>
        <mesh filename="package://car_meshes/meshes/body_collision.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>

  <joint name="${vehicle_bonnet}_joint" type="fixed">
    <origin xyz="${vehicle_bonnet_x} 0 ${vehicle_bonnet_z}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="${vehicle_bonnet}"/>
  </joint>
  <link name="${vehicle_bonnet}">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="0.1" ixy="0.0" ixz="0.0"
        iyy="0.1" iyz="0.0"
        izz="0.1"/>
    </inertial>
  </link>

  <joint name="rear_axle_joint" type="fixed">
    <origin xyz="${rear_axle_x} 0 ${rear_axle_z}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="rear_axle"/>
  </joint>
  <link name="rear_axle">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="0.1" ixy="0.0" ixz="0.0"
        iyy="0.1" iyz="0.0"
        izz="0.1"/>
    </inertial>
  </link>

  <joint name="${roof_datum}_joint" type="fixed">
    <origin xyz="${roof_datum_x} 0 ${roof_datum_z}" rpy="0 0 0"/>
    <parent link="rear_axle"/>
    <child link="${roof_datum}"/>
  </joint>
  <link name="${roof_datum}">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="0.1" ixy="0.0" ixz="0.0"
        iyy="0.1" iyz="0.0"
        izz="0.1"/>
    </inertial>
  </link>

  <link name="steer_fl">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.037227" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.06"/>
    </inertial>
  </link>

  <link name="steer_fr">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.037227" ixy="0" ixz="0" iyy="0.04" iyz="0" izz="0.06"/>
    </inertial>
  </link>

  <link name="wheel_fl">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_weight}"/>
      <inertia
        ixx="${(wheel_weight/12)*(3*(wheel_radius**2)+(wheel_width**2))}" ixy="0.0" ixz="0.0"
        iyy="${(wheel_weight/12)*(3*(wheel_radius**2)+(wheel_width**2))}" iyz="0.0"
        izz="${(wheel_weight*(wheel_radius**2))/2}" />
    </inertial>
    <visual name="wheel_fl_visual">
      <origin xyz="0 0 0" rpy="-${pi/2} ${pi/2} 0"/>
      <geometry>
        <mesh filename="package://car_meshes/meshes/mondeo_wheel.dae"/>
      </geometry>
      <material name="carpaint_002"/>
    </visual>
    <collision name="wheel_fl_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>1.2</mu>
              <mu2>1.2</mu2>
            </ode>
          </friction>
        </surface>
    </collision>
  </link>

  <link name="wheel_fr">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_weight}"/>
      <inertia
        ixx="${(wheel_weight/12)*(3*(wheel_radius**2)+(wheel_width**2))}" ixy="0.0" ixz="0.0"
        iyy="${(wheel_weight/12)*(3*(wheel_radius**2)+(wheel_width**2))}" iyz="0.0"
        izz="${(wheel_weight*(wheel_radius**2))/2}" />
    </inertial>
    <visual name="wheel_fr_visual">
      <origin xyz="0 0 0" rpy="-${pi/2} -${pi/2} 0"/>
      <geometry>
        <mesh filename="package://car_meshes/meshes/mondeo_wheel.dae"/>
      </geometry>
      <material name="carpaint_002.001"/>
    </visual>
    <collision name="wheel_fr_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>1.2</mu>
              <mu2>1.2</mu2>
            </ode>
          </friction>
        </surface>
    </collision>
  </link>

  <link name="wheel_rl">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_weight}"/>
      <inertia
        ixx="${(wheel_weight/12)*(3*(wheel_radius**2)+(wheel_width**2))}" ixy="0.0" ixz="0.0"
        iyy="${(wheel_weight/12)*(3*(wheel_radius**2)+(wheel_width**2))}" iyz="0.0"
        izz="${(wheel_weight*(wheel_radius**2))/2}" />
    </inertial>
    <visual name="wheel_rl_visual">
      <origin xyz="0 0 0" rpy="-${pi/2} ${pi/2} 0"/>
      <geometry>
        <mesh filename="package://car_meshes/meshes/mondeo_wheel.dae"/>
      </geometry>
      <material name="carpaint_002.003"/>
    </visual>
    <collision name="wheel_rl_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>1.2</mu>
              <mu2>1.2</mu2>
            </ode>
          </friction>
        </surface>
    </collision>
  </link>

  <link name="wheel_rr">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_weight}"/>
      <inertia
        ixx="${(wheel_weight/12)*(3*(wheel_radius**2)+(wheel_width**2))}" ixy="0.0" ixz="0.0"
        iyy="${(wheel_weight/12)*(3*(wheel_radius**2)+(wheel_width**2))}" iyz="0.0"
        izz="${(wheel_weight*(wheel_radius**2))/2}" />
    </inertial>
    <visual name="wheel_rr_visual">
      <origin xyz="0 0 0" rpy="-${pi/2} -${pi/2} 0"/>
      <geometry>
        <mesh filename="package://car_meshes/meshes/mondeo_wheel.dae"/>
      </geometry>
      <material name="carpaint_002.002"/>
    </visual>
    <collision name="wheel_rr_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>1.2</mu>
              <mu2>1.2</mu2>
            </ode>
          </friction>
        </surface>
    </collision>
  </link>

  <joint name="front_axle_joint" type="fixed">
    <origin xyz="${front_axle_x} 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="front_axle"/>
  </joint>
  <link name="front_axle">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="0.1" ixy="0.0" ixz="0.0"
        iyy="0.1" iyz="0.0"
        izz="0.1"/>
    </inertial>
  </link>

  <joint name="${front_bumper}_joint" type="fixed">
    <origin xyz="${front_bumper_x} 0 ${front_bumper_z}" rpy="0 0 0"/>
    <parent link="vehicle_bonnet"/>
    <child link="${front_bumper}"/>
  </joint>
  <link name="${front_bumper}">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia
        ixx="0.1" ixy="0.0" ixz="0.0"
        iyy="0.1" iyz="0.0"
        izz="0.1"/>
    </inertial>
  </link>

  <joint name="base_link" type="fixed">
    <origin xyz="${base_link_x} 0 ${base_link_z}" rpy="0 0 0"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  <joint name="steer_fl" type="revolute">
    <origin xyz="${front_axle_x} ${wheel_front_y} 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="steer_fl"/>
    <axis xyz="0 0 1.0"/>
    <limit lower="-0.6" upper="0.6" effort="10000" velocity="10"/>
  </joint>

  <joint name="steer_fr" type="revolute">
    <origin xyz="${front_axle_x} -${wheel_front_y} 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="steer_fr"/>
    <axis xyz="0 0 1.0"/>
    <limit lower="-0.6" upper="0.6" effort="10000" velocity="10"/>
  </joint>

  <joint name="wheel_fl" type="continuous">
    <origin xyz="0 0 0" rpy="${pi/2} 0 -${pi}"/>
    <parent link="steer_fl"/>
    <child link="wheel_fl"/>
    <axis xyz="0 0 1.0"/>
    <limit dissipation="1" effort="1000.0" velocity="${48*pi}"/> <!-- ~40mph -->
  </joint>

  <joint name="wheel_fr" type="continuous">
    <origin xyz="0 0 0" rpy="${pi/2} 0 -${pi}"/>
    <parent link="steer_fr"/>
    <child link="wheel_fr"/>
    <axis xyz="0 0 1.0"/>
    <limit dissipation="1" effort="1000.0" velocity="${48*pi}"/> <!-- ~40mph -->
  </joint>

  <joint name="wheel_rl" type="continuous">
    <origin xyz="-${front_axle_x} ${wheel_rear_y} 0" rpy="${pi/2} 0 -${pi}"/>
    <parent link="base_link"/>
    <child link="wheel_rl"/>
    <axis xyz="0 0 1.0"/>
    <limit dissipation="1" effort="1000.0" velocity="${48*pi}"/> <!-- ~40mph -->
  </joint>

  <joint name="wheel_rr" type="continuous">
    <origin xyz="-${front_axle_x} -${wheel_rear_y} 0" rpy="${pi/2} 0 -${pi}"/>
    <parent link="base_link"/>
    <child link="wheel_rr"/>
    <axis xyz="0 0 1.0"/>
    <limit dissipation="1" effort="1000.0" velocity="${48*pi}"/> <!-- ~40mph -->
  </joint>

  <!-- Footprint Frames -->
  <joint name="footprint_fl_joint" type="fixed">
    <origin xyz="${footprint_front_x} ${footprint_y} 0" rpy="0 0 0"/>
    <parent link="rear_axle"/>
    <child link="footprint_fl"/>
  </joint>
  <link name="footprint_fl"/>

  <joint name="footprint_fr_joint" type="fixed">
    <origin xyz="${footprint_front_x} ${-footprint_y} 0" rpy="0 0 0"/>
    <parent link="rear_axle"/>
    <child link="footprint_fr"/>
  </joint>
  <link name="footprint_fr"/>

  <joint name="footprint_rl_joint" type="fixed">
    <origin xyz="${footprint_rear_x} ${footprint_y} 0" rpy="0 0 0"/>
    <parent link="rear_axle"/>
    <child link="footprint_rl"/>
  </joint>
  <link name="footprint_rl"/>

  <joint name="footprint_rr_joint" type="fixed">
    <origin xyz="${footprint_rear_x} ${-footprint_y} 0" rpy="0 0 0"/>
    <parent link="rear_axle"/>
    <child link="footprint_rr"/>
  </joint>
  <link name="footprint_rr"/>

  <material name="black.001">
    <color rgba="0 0 0 1.0"/>
  </material>

  <material name="carpaint_002">
    <color rgba="0.941177 0.941177 0.941177 1.0"/>
  </material>

  <material name="carpaint_002.001">
    <color rgba="0.941177 0.941177 0.941177 1.0"/>
  </material>

  <material name="carpaint_002.002">
    <color rgba="0.941177 0.941177 0.941177 1.0"/>
  </material>

  <material name="carpaint_002.003">
    <color rgba="0.941177 0.941177 0.941177 1.0"/>
  </material>

</robot>
